'use client';
import { useEffect, useRef, useState } from 'react';
import { Baby, Check, ChevronDown, ChevronUp, Circle, CloudRain, Coffee, Heart, MapPin, Moon, Navigation, Pencil, Plus, Route, Search, SkipForward, Ticket, TrainFront, Plane, BedDouble, Sparkles, WifiOff, Download, Umbrella } from 'lucide-react';
import { days, itinerary, sourceNotes, trip } from '@/data/trip';
import { places as basePlaces, categoryLabels, collections, foodPreference } from '@/data/places';
import { bookings as baseBookings } from '@/data/bookings';
import { bookingLabels, priorityLabels, mapsUrl, safeUrl, countdown, localClock, mergeItems, mergePlaces, placeQuery, dayItems, nextActivity, simpleDay, changeItem, changeBooking, reorder, STORAGE_KEY } from '@/lib/itinerary';
import { useTrip } from '@/lib/use-trip';
import type { Booking, Category, ItineraryItem, Place, PlanReason, LocalState } from '@/lib/types';
import { Sheet, ItemEditor, BookingEditor, PlaceEditor } from '@/components/editor';
import { useWebMCP } from '@/lib/webmcp';

type Tab = 'itinerary'|'bookings'|'map'|'places';
const tabs = [{id:'itinerary',zh:'行程',en:'Itinerary',Icon:Route},{id:'bookings',zh:'预订',en:'Bookings',Icon:Ticket},{id:'map',zh:'地图',en:'Map',Icon:MapPin},{id:'places',zh:'收藏',en:'Places',Icon:Heart}] as const;
const reasons: {id:PlanReason;label:string;Icon:typeof Baby}[]=[{id:'rain',label:'下雨',Icon:CloudRain},{id:'tired',label:'Remi 累了',Icon:Moon},{id:'late',label:'行程晚了',Icon:Coffee},{id:'unavailable',label:'景点没进去',Icon:Ticket}];
const bookingGroups=[{id:'flights',label:'航班',en:'Flights',Icon:Plane},{id:'hotels',label:'住宿',en:'Hotels',Icon:BedDouble},{id:'trains',label:'高铁',en:'Trains',Icon:TrainFront},{id:'attractions',label:'景点门票',en:'Attractions',Icon:Ticket},{id:'activities',label:'亲子活动',en:'Activities',Icon:Sparkles}] as const;
function MapLink({query,label='导航',className='map-link'}:{query?:string;label?:string;className?:string}) {return query?<a className={className} href={mapsUrl(query)} target="_blank" rel="noopener noreferrer" aria-label={`Google Maps ${label}：${query}`}><Navigation size={16}/>{label}</a>:null;}
function Status({status}:{status:ItineraryItem['bookingStatus']}) {return <span className={`badge status-${status}`}>{status==='booked'&&<Check size={12}/>} {bookingLabels[status]||'待确认'}</span>;}
function FamilyTags({item}:{item:Partial<ItineraryItem>}) {return <div className="family-tags">{item.childFriendly&&<span><Baby size={14}/>适合 Remi</span>}{item.strollerFriendly&&<span>推车友好</span>}{item.napFriendly&&<span><Moon size={13}/>适合推车午睡</span>}{item.freePlay&&<span>自由玩耍</span>}{item.indoor&&<span><Umbrella size={13}/>室内备用</span>}{item.bathrooms&&<span className="bathroom">洗手间：{item.bathrooms}</span>}</div>;}

export default function Home() {
 const {state,update,ready,saveError,offlineReady,online}=useTrip();
 const [tab,setTab]=useState<Tab>('itinerary'),[selectedDate,setSelectedDate]=useState('2026-10-23');
 const [now,setNow]=useState<Date|null>(null),[editMode,setEditMode]=useState(false),[tired,setTired]=useState(false);
 const [planReason,setPlanReason]=useState<PlanReason|null>(null),[nextOpen,setNextOpen]=useState(false),[overview,setOverview]=useState(false);
 const [editingItem,setEditingItem]=useState<ItineraryItem|null>(null),[editingBooking,setEditingBooking]=useState<Booking|null>(null),[addingPlace,setAddingPlace]=useState(false);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState<Category|'all'|'remi'>('all'),[onlyFavorites,setOnlyFavorites]=useState(false),[mapScope,setMapScope]=useState<'day'|'all'>('day');
 const [toast,setToast]=useState('');
 const nextRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  const date=new Date();setNow(date);
  const current=days.find(d=>localClock(date,d.timeZone).date===d.date);if(current)setSelectedDate(current.date);
  const fromHash=window.location.hash.slice(1);if(tabs.some(t=>t.id===fromHash))setTab(fromHash as Tab);
  const hash=()=>{const value=window.location.hash.slice(1);if(tabs.some(t=>t.id===value))setTab(value as Tab);};window.addEventListener('hashchange',hash);
  const timer=window.setInterval(()=>setNow(new Date()),30000);
  return ()=>{clearInterval(timer);window.removeEventListener('hashchange',hash);};
 },[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{document.querySelector('.date.active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});},[selectedDate]);
 const places=mergePlaces(basePlaces,state,baseBookings);
 const bookings=baseBookings.map(b=>({...b,...state.bookingEdits[b.id]}));
 const items=mergeItems(itinerary,places,bookings,state);
 const day=days.find(d=>d.date===selectedDate)!;
 const selectedItems=dayItems(items,selectedDate,state);
 const next=now?nextActivity(selectedItems,day,state,now):{item:selectedItems[0],mode:'preview'};
 const visibleItems=tired&&now?simpleDay(selectedItems,day,state,now):selectedItems;
 const hotel=places.find(p=>p.id===day.hotelId);
 const dayPlaceIds=new Set(selectedItems.map(item=>item.placeId));
 const hotelBooking=bookings.find(b=>b.type==='hotels'&&b.placeId===day.hotelId);
 const today=now?localClock(now,day.timeZone).date===selectedDate:false;
 const count=now?countdown(now,trip.startDate):null;
 const nav=(value:Tab)=>{setTab(value);window.location.hash=value;setSearch('');setFilter('all');};
 const selectDate=(date:string)=>{setSelectedDate(date);setTired(false);};
 const mutate=(apply:(s:LocalState)=>LocalState,message?:string)=>{update(apply);if(message)setToast(message);};
 const progress=(item:ItineraryItem,value:'completed'|'skipped')=>mutate(s=>{const p={...s.progress};if(p[item.id]===value)delete p[item.id];else p[item.id]=value;return {...s,progress:p};});
 const addActivity=(place?:Place)=>setEditingItem({id:'new',date:selectedDate,title:place?.name||'',titleZh:place?.nameZh,placeId:place?.id,category:place?.category||'attractions',priority:place?.priority||'optional',bookingStatus:place?.availability==='sold-out'?'sold-out':'tbd',childFriendly:place?.childFriendly,strollerFriendly:place?.strollerFriendly,napFriendly:place?.napFriendly,indoor:place?.indoor});
 useWebMCP({state,items,days,selectedDate,selectDate,update,ready});
 const filtered=places.filter(p=>(filter==='all'||filter==='remi'?(filter!=='remi'||p.tags?.includes('REMI')):p.category===filter)&&(!onlyFavorites||tab==='map'||state.favorite[p.id])&&(!search||[p.name,p.nameZh,p.neighborhood,p.address,p.notes,state.placeNotes[p.id]].join(' ').toLowerCase().includes(search.toLowerCase()))&&(tab!=='map'||mapScope==='all'||dayPlaceIds.has(p.id)));
 const saveItem=(patch:Partial<ItineraryItem>)=>{
  if(!editingItem)return;
  if(editingItem.id==='new')mutate(s=>({...s,addedItems:[...s.addedItems,{...editingItem,...patch,id:`activity-${crypto.randomUUID()}`}]}),'已添加到行程');
  else mutate(s=>changeItem(s,editingItem,patch),'活动已保存');
  if(patch.date)setSelectedDate(patch.date);setEditingItem(null);
 };
 function exportBackup(){let raw=JSON.stringify(state,null,2);if(saveError.includes('原数据')){try{raw=localStorage.getItem(STORAGE_KEY)||raw;}catch{/* Use the current in-memory state when storage is unavailable. */}}const blob=new Blob([raw],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='spain-journal-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const nextPanel=next.item?<><span className="eyebrow">{next.mode==='overdue'?'时间已过 · 请确认是否继续':next.mode==='today'?'下一站 · NEXT STOP':next.mode==='past'?'这一天 · 尚未完成':'这一天的下一站'}</span><h3>{next.item.startTime&&<span className="next-time">{next.item.startTime} · </span>}{next.item.titleZh||next.item.title}</h3><p>{next.item.duration||next.item.timeNote||'时间灵活'}{next.item.duration&&next.item.timeNote?' · '+next.item.timeNote:''}</p><div className="next-status"><Status status={next.item.bookingStatus}/></div></>:<><span className="eyebrow">今日留白</span><h3>接下来，好好休息。</h3><p>没有待开始的活动了。随时查看清单或回住处。</p></>;
 return <div className="app-shell">
  <header className="masthead"><button className="wordmark" onClick={()=>setOverview(true)}>西班牙慢游<span>OUR FAMILY JOURNAL</span></button><button className="trip-year" onClick={()=>setOverview(true)} aria-label="旅行概览与离线状态">{!online?<><WifiOff size={14}/> 离线</>:offlineReady?'已可离线使用':'EST. 2026'}</button></header>
  <section className="trip-cover"><div className="cover-text"><span className="eyebrow">A LITTLE ADVENTURE, TOGETHER</span><h1>SPAIN<span>西班牙，一起慢慢走。</span></h1><p>22–29 OCTOBER 2026</p><div className="cover-meta">Barcelona · Madrid <span>2 位大人 + 小小 Remi</span></div></div><div className="cover-photo" role="img" aria-label="桂尔公园的彩色马赛克建筑与巴塞罗那全景"/></section>
  <main>
  {saveError&&<div className="save-error" role="alert">{saveError}<button onClick={exportBackup}>导出本机备份</button></div>}
  {count!==null&&count>0&&<div className="countdown"><span className="tiny-sun">✳</span> 距离西班牙旅行还有 <strong>{count}</strong> 天 <span className="countdown-end">慢慢期待，好好出发。</span></div>}
  {(tab==='itinerary'||tab==='map')&&<div className="date-strip" aria-label="选择行程日期">{days.map(d=><button key={d.date} className={selectedDate===d.date?'date active':'date'} aria-pressed={selectedDate===d.date} aria-label={`10月${d.date.slice(-2)}日 ${d.weekdayZh}`} onClick={()=>selectDate(d.date)}><small>{d.weekday}</small><strong>{d.date.slice(-2)}</strong><span>10 月</span>{now&&localClock(now,d.timeZone).date===d.date&&<i/>}</button>)}</div>}
  {!ready?<p className="loading" role="status">正在打开你的旅行手帐…</p>:tab==='itinerary'?<div className="content-grid"><section aria-label="每日行程">
   <div className="day-heading"><div><div className="eyebrow">{today?'TODAY · ':`DAY ${String(days.indexOf(day)+1).padStart(2,'0')} · `}{day.weekday} / {day.weekdayZh}</div><h2 className={day.city.length>12?'long-city':''}>{day.city}<span>{day.cityZh}</span></h2><p>{day.theme}</p></div><button className={'icon-button '+(editMode?'enabled':'')} onClick={()=>setEditMode(!editMode)} aria-label={editMode?'结束编辑':'编辑行程'} aria-pressed={editMode}><Pencil size={18}/></button></div>
   <div className="remi-controls"><button className="remi-toggle" role="switch" aria-checked={state.remiMode} onClick={()=>mutate(s=>({...s,remiMode:!s.remiMode}))}><Baby size={21}/> Remi Mode <span className={'switch '+(state.remiMode?'on':'')}/></button><button className={'text-button '+(tired?'active':'')} aria-pressed={tired} onClick={()=>setTired(!tired)}>{tired?'查看完整一天':'Remi 累了'}</button><button className="text-button" onClick={()=>setPlanReason('rain')}><CloudRain size={16}/> Plan B</button></div>
   {tired&&<div className="gentle-note"><Moon size={18}/><span>轻松一点：保留必做、吃饭和省力的停留。已完成和跳过的活动已收起。</span></div>}
   <div className="next-card" ref={nextRef}><div>{nextPanel}</div>{next.item?.googleMapsQuery&&<MapLink query={next.item.googleMapsQuery} className="nav-button"/>}</div>
   <button className="whats-next" onClick={()=>{setNow(new Date());setNextOpen(true);}}><Route size={17}/>接下来做什么？<span>{today?'按当地时间':'预览所选日期'}</span></button>
   {day.checklist&&<section className="checklist"><h3>{selectedDate==='2026-10-29'?'出发前，一步一步来':'出发准备清单'}</h3>{day.checklist.map(check=><label key={check.id}><input type="checkbox" checked={!!state.checks[`${day.date}-${check.id}`]} onChange={()=>mutate(s=>({...s,checks:{...s.checks,[`${day.date}-${check.id}`]:!s.checks[`${day.date}-${check.id}`]}}))}/><span>{check.label}</span></label>)}{selectedDate==='2026-10-29'&&<a className="source-link" href={sourceNotes.taxRefund} target="_blank" rel="noreferrer">查看 Aena 官方退税流程</a>}</section>}
   <div className="section-caption"><span>{tired?'剩下的轻松行程':'今天的节奏'}</span><small>{selectedItems.filter(i=>state.progress[i.id]==='completed').length} / {selectedItems.length} 已完成</small></div>
   {editMode&&<div className="edit-banner"><p>用上下按钮调整路线；编辑卡片可改时间、移到另一天。</p><button onClick={()=>addActivity()}><Plus size={17}/>添加活动</button></div>}
   <div className="timeline">{visibleItems.map((item,index)=>{
    const completed=state.progress[item.id]==='completed',skipped=state.progress[item.id]==='skipped';
    return <article className={'timeline-row '+(completed||skipped?'is-done ':'')+(state.remiMode&&item.demanding&&item.priority==='optional'?'demanding ':'')} key={item.id} data-testid={`activity-${item.id}`}>
    <div className="time"><strong>{item.startTime||'待定'}</strong><span>{item.endTime||(!item.startTime?'灵活安排':item.bookingStatus==='booked'?'已安排':'计划时间')}</span></div>
    <div className={'activity-card '+(state.remiMode&&item.childFriendly?'child-highlight':'')}><div className="activity-top"><div className="card-badges"><span className={'badge '+(item.priority==='must'?'must':'')}>{priorityLabels[item.priority]}</span>{item.bookingStatus!=='no-reservation'&&<Status status={item.bookingStatus}/>}</div><button className={'complete '+(completed?'checked':'')} aria-label={`${completed?'取消完成':'完成'} ${item.titleZh||item.title}`} aria-pressed={completed} onClick={()=>progress(item,'completed')}>{completed?<Check size={21}/>:skipped?<SkipForward size={19}/>:<Circle size={21}/>}</button></div>
    <h3>{item.titleZh||item.title}</h3>{item.titleZh&&<p className="original-title">{item.title}</p>}{skipped&&<span className="badge skipped">已跳过 · 可恢复</span>}
    <p className="description">{item.description}</p>{item.timeNote&&<p className="time-note">{item.timeNote}</p>}
    {(state.remiMode||item.napFriendly)&&<FamilyTags item={state.remiMode?item:{napFriendly:item.napFriendly}}/>}
    {item.notes&&<p className="personal-note">{item.notes}</p>}
    <div className="card-footer"><span>{item.duration||item.neighborhood||categoryLabels[item.category]}</span><MapLink query={item.googleMapsQuery}/></div>
    <details className="activity-details"><summary>更多信息与备注<ChevronDown size={14}/></summary><div className="details-body">{item.address&&<p><MapPin size={15}/>{item.address}</p>}{item.walkingContext&&<p>{item.walkingContext}</p>}<p>预订：{bookingLabels[item.bookingStatus]}{item.confirmationNumber?' · 确认号 '+item.confirmationNumber:''}</p>{item.indoor!==undefined&&<p>{item.indoor?'室内活动':'户外活动'}</p>}{item.bathrooms&&<p>洗手间：{item.bathrooms}</p>}{safeUrl(item.ticketUrl)&&<a className="outline-button" href={safeUrl(item.ticketUrl)} target="_blank" rel="noreferrer"><Ticket size={16}/>打开票券</a>}{safeUrl(item.bookingUrl)&&<a className="source-link" href={safeUrl(item.bookingUrl)} target="_blank" rel="noreferrer">官方 / 预订信息</a>}<div className="detail-actions"><button onClick={()=>setEditingItem(item)}><Pencil size={15}/>编辑 / 加笔记</button><button onClick={()=>progress(item,'skipped')}><SkipForward size={15}/>{skipped?'恢复活动':'跳过'}</button>{item.bookingStatus==='need-to-book'&&<button onClick={()=>mutate(s=>changeItem(s,item,{bookingStatus:'booked'}),'已标为预订')}><Check size={15}/>标为已预订</button>}</div></div></details>
    {editMode&&<div className="reorder"><button aria-label={`上移 ${item.titleZh||item.title}`} disabled={index===0} onClick={()=>mutate(s=>reorder(s,selectedItems,item.id,-1))}><ChevronUp size={19}/></button><button aria-label={`下移 ${item.titleZh||item.title}`} disabled={index===visibleItems.length-1} onClick={()=>mutate(s=>reorder(s,selectedItems,item.id,1))}><ChevronDown size={19}/></button><button onClick={()=>setEditingItem(item)}>编辑活动</button><button onClick={()=>progress(item,'skipped')}>{skipped?'恢复':'跳过'}</button></div>}
    </div></article>;
   })}</div>
   {visibleItems.length===0&&<div className="empty"><Coffee size={28}/><h3>余下时间，留给休息。</h3><p>可以回住处，或从收藏里选一个轻松的地点。</p></div>}
   {tired&&hotel&&<div className="return-card"><BedDouble size={22}/><div><span>随时回去休息</span><h3>{hotel.name}</h3>{hotel.needsVerification&&<small>准确地址待补充，请先核对订单</small>}</div><MapLink query={placeQuery(hotel)}/></div>}
   <button className="add-activity" onClick={()=>addActivity()}><Plus size={18}/>为这一天添加活动</button>
   <details className="mobile-day-note"><summary>今日提醒与住宿</summary><p>{day.note}</p>{hotel&&<><h4>{hotel.name}</h4><MapLink query={hotelBooking?.address||placeQuery(hotel)}/></>}</details>
  </section><aside><div className="aside-card"><span className="eyebrow">OUR TRIP, AT A GLANCE</span><h3>八天，三个人。</h3><p>2 位大人 · Remi，3 岁</p><p>3 件大行李箱 · 1 辆推车</p>{hotel&&<><hr/><MapPin size={20}/><h4>今晚住这里</h4><p>{hotel.name}</p><Status status={hotelBooking?.status||'tbd'}/><MapLink query={hotelBooking?.address||placeQuery(hotel)}/></>}<button className="aside-overview" onClick={()=>setOverview(true)}>旅行概览与离线使用</button></div><div className="aside-note"><span>一点小提醒</span><p>{day.note}</p></div><div className="route-note"><span className="eyebrow">LOCAL TIME</span><p>{now?localClock(now,day.timeZone).time:'—'} <small>{day.timeZone==='Europe/Madrid'?'西班牙时间':'纽约时间'}</small></p></div></aside></div>
  :tab==='bookings'?<section className="bookings-view"><div className="page-heading"><span className="eyebrow">EVERYTHING IN ONE PLACE</span><h2>旅途里的，每一张票。</h2><p>订好了的安心收着，待确认的慢慢补齐。</p></div><div className="booking-summary"><span><strong>{bookings.filter(b=>b.status==='booked').length}</strong> 已预订</span><span><strong>{bookings.filter(b=>b.status==='need-to-book').length}</strong> 待预订</span><span><strong>{bookings.filter(b=>b.status==='sold-out').length}</strong> 留意退票</span></div><div className="booking-groups">{bookingGroups.map(group=><section key={group.id} className="booking-group"><h3><group.Icon size={20}/>{group.label}<span>{group.en}</span></h3>{bookings.filter(b=>b.type===group.id).map(booking=>{
    const place=places.find(p=>p.id===booking.placeId);
    return <article className="booking-card" key={booking.id}><div className="booking-card-top"><span className="booking-date">{booking.date.slice(5).replace('-',' / ')}{booking.endDate?' – '+booking.endDate.slice(5).replace('-',' / '):''}</span><Status status={booking.status}/></div><h4>{booking.title}</h4><p className="booking-time">{booking.time||'时间待定'}{booking.timeNote?' · '+booking.timeNote:''}</p>{booking.confirmationNumber&&<p className="confirmation">确认号 <strong>{booking.confirmationNumber}</strong></p>}<p className="description">{booking.notes}</p><div className="booking-actions">{safeUrl(booking.ticketUrl)?<a className="outline-button" href={safeUrl(booking.ticketUrl)} target="_blank" rel="noreferrer"><Ticket size={15}/>打开票券</a>:<span className="ticket-missing">票券尚未添加</span>}{safeUrl(booking.reservationUrl)&&<a className="source-link" href={safeUrl(booking.reservationUrl)} target="_blank" rel="noreferrer">官网 / 预订</a>}<button className="icon-button" aria-label={`编辑预订 ${booking.title}`} onClick={()=>setEditingBooking(booking)}><Pencil size={16}/></button></div><details className="activity-details"><summary>地址、取消政策与票券<ChevronDown size={14}/></summary><div className="details-body"><p>{booking.address||place?.address||'准确地址以订单为准'}</p>{place&&<MapLink query={booking.address||placeQuery(place)}/>}<p>{booking.cancellationNotes||'退改政策待从订单补充。'}</p>{booking.ticketImage?<img className="ticket-image" src={booking.ticketImage} alt={`${booking.title} 票券二维码`}/>:<p>尚无本地票券图片，可先在编辑中填写票券链接。</p>}</div></details></article>;
   })}</section>)}</div></section>
  :<section className="places-view"><div className="page-heading"><span className="eyebrow">{tab==='map'?'FOLLOW YOUR CURIOSITY':'LITTLE PLACES, LOVELY MEMORIES'}</span><div className="heading-row"><h2>{tab==='map'?'下一站，在这里。':'想去的地方。'}</h2>{tab==='places'&&<button className="icon-button" aria-label="添加新地点" onClick={()=>setAddingPlace(true)}><Plus size={20}/></button>}</div><p>{tab==='map'?'按街区找地点，一键打开 Google Maps。':'小店、好吃的，还有 Remi 的快乐。'}</p></div>
    {tab==='map'&&<div className="segmented"><button className={mapScope==='day'?'active':''} onClick={()=>setMapScope('day')}>10/{selectedDate.slice(-2)} 的地点</button><button className={mapScope==='all'?'active':''} onClick={()=>setMapScope('all')}>全部地点</button></div>}
    <label className="search-box"><Search size={19}/><input aria-label="搜索地点" placeholder="搜索名字、街区，或你的笔记" value={search} onChange={e=>setSearch(e.target.value)}/></label>
    <div className="filter-strip" aria-label="地点类别筛选"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>全部</button>{(Object.entries(categoryLabels) as [Category,string][]).map(([id,label])=><button className={filter===id?'active':''} key={id} onClick={()=>setFilter(id)}>{label}</button>)}<button className={filter==='remi'?'active':''} onClick={()=>setFilter('remi')}><Baby size={15}/>REMI</button></div>
    <div className="places-toolbar"><span>{filtered.length} 个地点</span>{tab==='places'&&<button aria-pressed={onlyFavorites} className={onlyFavorites?'active':''} onClick={()=>setOnlyFavorites(!onlyFavorites)}><Heart size={16} fill={onlyFavorites?'currentColor':'none'}/>只看心选</button>}</div>
    {filtered.length===0&&<div className="empty"><Search size={26}/><h3>还没有符合条件的地点</h3><p>换个关键词或筛选，或添加你发现的新地方。</p></div>}
    <div className="place-grid">{filtered.map(place=><article className={'place-card '+(state.visited[place.id]?'visited':'')} key={place.id}><div className="place-card-top"><span className="eyebrow">{categoryLabels[place.category]} · {place.neighborhood}</span><button className="favorite-button" aria-label={`${state.favorite[place.id]?'取消收藏':'收藏'} ${place.name}`} aria-pressed={!!state.favorite[place.id]} onClick={()=>mutate(s=>({...s,favorite:{...s.favorite,[place.id]:!s.favorite[place.id]}}))}><Heart size={20} fill={state.favorite[place.id]?'currentColor':'none'}/></button></div><h3>{place.nameZh||place.name}</h3>{place.nameZh&&<p className="original-title">{place.name}</p>}<div className="place-badges"><span className={'badge '+(place.priority==='must'?'must':'')}>{place.priority==='must'?'Must · 必去':place.priority==='recommended'?'Want to visit · 想去':'If nearby · 顺路再去'}</span>{place.availability&&<span className="badge status-sold-out">{place.availability==='unavailable'?'旅行期间不可用':'线上售罄'}</span>}{place.tags?.includes('REMI')&&<span className="badge remi">REMI</span>}</div>{place.address&&<p className="place-address">{place.address}</p>}{place.walkingContext&&<p className="description">{place.walkingContext}</p>}{place.needsVerification&&<p className="verification-note">具体地址 / 营业待确认</p>}{place.notes&&<p className="description">{place.notes}</p>}<div className="place-actions"><button className={state.visited[place.id]?'visited-control selected':'visited-control'} onClick={()=>mutate(s=>({...s,visited:{...s.visited,[place.id]:!s.visited[place.id]}}))} aria-pressed={!!state.visited[place.id]}>{state.visited[place.id]?<Check size={16}/>:<Circle size={16}/>}去过了</button><MapLink query={placeQuery(place)}/></div><details className="activity-details"><summary>笔记与行程安排<ChevronDown size={14}/></summary><div className="details-body"><label className="place-note-label">我的笔记<textarea aria-label={`${place.name} 的笔记`} value={state.placeNotes[place.id]||''} onChange={e=>mutate(s=>({...s,placeNotes:{...s.placeNotes,[place.id]:e.target.value}}))} rows={2} maxLength={6000} placeholder="记下喜欢的款式、想吃的菜…"/></label><FamilyTags item={place}/><button className="outline-button" disabled={place.availability==='unavailable'} onClick={()=>addActivity(place)}><Plus size={16}/>安排到某一天</button></div></details></article>)}</div>
    {tab==='places'&&<><div className="food-preference"><Coffee size={20}/><p>{foodPreference}</p></div><div className="collections">{collections.map(collection=><div key={collection.title}><h3>{collection.title}</h3><p className="field-help">还没选具体店，留待发现。</p><div>{collection.categories.map(label=><span key={label}>{label}</span>)}</div></div>)}</div></>}
  </section>}
  <footer className="journal-footer"><span>一点计划，多一点随心。</span><button onClick={()=>setOverview(true)}>旅行概览 · 离线使用 · 图片来源</button></footer>
  </main>
  <nav className="bottom-nav" aria-label="主导航">{tabs.map(({id,zh,en,Icon})=><button key={id} className={tab===id?'selected':''} aria-current={tab===id?'page':undefined} onClick={()=>nav(id)}><Icon size={21}/><span>{zh}<small>{en}</small></span></button>)}</nav>
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {editingItem&&<ItemEditor item={editingItem} days={days} places={places} onSave={saveItem} onClose={()=>setEditingItem(null)}/>}
  {editingBooking&&<BookingEditor booking={editingBooking} days={days} onSave={patch=>{mutate(s=>changeBooking(s,editingBooking,patch,items),'预订已保存');setEditingBooking(null);}} onClose={()=>setEditingBooking(null)}/>}
  {addingPlace&&<PlaceEditor onClose={()=>setAddingPlace(false)} onSave={place=>{mutate(s=>({...s,addedPlaces:[...s.addedPlaces,place]}),'地点已保存');setAddingPlace(false);setFilter('all');setSearch('');setOnlyFavorites(false);}}/>}
  {nextOpen&&<Sheet title="接下来做什么？" description={`${day.date.slice(5).replace('-','/')} · ${day.cityZh} · ${today?'按当地时间计算':'预览所选日期，不代表今天'}`} onClose={()=>setNextOpen(false)}><div className="next-detail">{nextPanel}{next.item&&<><p className="description">{next.item.description}</p>{next.item.walkingContext&&<p className="walking-context">{next.item.walkingContext}</p>}<FamilyTags item={next.item}/><MapLink query={next.item.googleMapsQuery} className="primary-button" label="Google Maps 导航"/><div className="detail-actions"><button onClick={()=>{progress(next.item!,'completed');}}>已完成，看看下一站</button><button onClick={()=>progress(next.item!,'skipped')}>跳过这一站</button></div></>}{!next.item&&hotel&&<MapLink query={placeQuery(hotel)} label="回住处"/>}</div></Sheet>}
  {planReason&&<Sheet title="计划有变，也没关系。" description={`${day.date.slice(5).replace('-','/')} · Plan B · 只显示这一天的备选`} onClose={()=>setPlanReason(null)}><div className="plan-reasons">{reasons.map(({id,label,Icon})=><button key={id} className={planReason===id?'active':''} onClick={()=>setPlanReason(id)}><Icon size={19}/>{label}</button>)}</div><div className="plan-options">{day.planB.filter(p=>p.reasons.includes(planReason)).map(plan=>{const place=places.find(p=>p.id===plan.placeId);return <article key={plan.id}><span className="eyebrow">{place?.neighborhood||'轻松一点'}</span><h3>{plan.title}</h3><p>{plan.description}</p>{place&&<MapLink query={placeQuery(place)}/>}</article>;})}</div>{planReason==='tired'&&<button className="primary-button" onClick={()=>{setTired(true);setPlanReason(null);}}>切换到轻松行程</button>}</Sheet>}
  {overview&&<Sheet title="我们的西班牙旅行" description="22–29 OCTOBER 2026 · Barcelona & Madrid" onClose={()=>setOverview(false)}><div className="overview"><h3>2 位大人 + Remi（3 岁）</h3><p>3 件大行李箱 · 1 辆推车</p><div className="overview-route"><span>10/22 · Newark 出发</span><span>10/23–28 · Barcelona</span><span>10/28–29 · Madrid</span><span>10/29 · 飞往 Chongqing</span></div><h3>随身使用</h3><p>{offlineReady?'此设备已缓存应用和行程，可离线查看。':'离线缓存尚未就绪。正式版本首次联网打开后会缓存行程。'}</p><p>在 iPhone Safari 打开正式 HTTPS 网址，点「分享」→「添加到主屏幕」。首次保持联网，等顶部显示「已可离线使用」。</p><p>导航与外部购票仍需要网络。修改只存在这台设备的这个浏览器，清除网站数据会删除修改；家人之间不会自动同步。</p><button className="outline-button" onClick={exportBackup}><Download size={17}/>导出本机备份</button><h3>尚需你补齐</h3><p>两段航班准确时间、公寓地址与门禁、确认号及票券。候选活动的场次、余票与店铺营业需确认；已预订状态按你提供的信息记录。</p><h3>图片与资料</h3><p className="photo-credit">首页采用你提供的桂尔公园图片。</p><a className="source-link" href={sourceNotes.taxRefund} target="_blank" rel="noreferrer">Aena 官方退税流程</a></div></Sheet>}
 </div>;
}
