'use client';
import { useLocale, LanguageProvider, LanguageSwitch } from '@/lib/language';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
const DailyRouteMap=dynamic(()=>import('@/components/daily-route-map'),{ssr:false,loading:()=> <div className="map-loading" role="status">◌ Map / 地图…</div>});
import { Baby, Check, ChevronDown, ChevronUp, Circle, CloudRain, Coffee, Heart, MapPin, Moon, Navigation, Pencil, Plus, Route, Search, SkipForward, Ticket, TrainFront, Plane, BedDouble, Sparkles, WifiOff, Download, Umbrella } from 'lucide-react';
import { days, itinerary, sourceNotes, trip } from '@/data/trip';
import { places as basePlaces, categoryLabels, collections, foodPreference } from '@/data/places';
import { bookings as baseBookings } from '@/data/bookings';
import { bookingLabels, priorityLabels, mapsUrl, safeUrl, countdown, localClock, mergeItems, mergePlaces, placeQuery, dayItems, nextActivity, simpleDay, changeItem, changeBooking, reorder, STORAGE_KEY } from '@/lib/itinerary';
import { useTrip } from '@/lib/use-trip';
import type { Booking, Category, ItineraryItem, Place, PlanReason, LocalState } from '@/lib/types';
import { Sheet, ItemEditor, BookingEditor, PlaceEditor } from '@/components/editor';
import { useWebMCP } from '@/lib/webmcp';

type Tab = 'itinerary'|'bookings'|'map'|'places';
const tabs = [{id:'itinerary',zh:'行程',en:'Itinerary',Icon:Route},{id:'bookings',zh:'预订',en:'Bookings',Icon:Ticket},{id:'map',zh:'地图',en:'Map',Icon:MapPin},{id:'places',zh:'收藏',en:'Places',Icon:Heart}] as const;
const reasons: {id:PlanReason;label:string;Icon:typeof Baby}[]=[{id:'rain',label:'下雨',Icon:CloudRain},{id:'tired',label:'Remi 累了',Icon:Moon},{id:'late',label:'行程晚了',Icon:Coffee},{id:'unavailable',label:'景点没进去',Icon:Ticket}];
const bookingGroups=[{id:'flights',label:'航班',en:'Flights',Icon:Plane},{id:'hotels',label:'住宿',en:'Hotels',Icon:BedDouble},{id:'trains',label:'高铁',en:'Trains',Icon:TrainFront},{id:'attractions',label:'景点门票',en:'Attractions',Icon:Ticket},{id:'activities',label:'亲子活动',en:'Activities',Icon:Sparkles}] as const;
function MapLink({query,label='导航',className='map-link'}:{query?:string;label?:string;className?:string}) {
 const {t}=useLocale();return query?<a className={className} href={mapsUrl(query)} target="_blank" rel="noopener noreferrer" aria-label={`Google Maps ${t(label)}：${query}`}><Navigation size={16}/>{t(label)}</a>:null;}
function Status({status}:{status:ItineraryItem['bookingStatus']}) {
 const {t}=useLocale();return <span className={`badge status-${status}`}>{status==='booked'&&<Check size={12}/>} {t(bookingLabels[status]||'待确认')}</span>;}
function FamilyTags({item}:{item:Partial<ItineraryItem>}) {
 const {t,display}=useLocale();return <div className="family-tags">{item.childFriendly&&<span><Baby size={14}/>{t("适合 Remi")}</span>}{item.strollerFriendly&&<span>{t("推车友好")}</span>}{item.napFriendly&&<span><Moon size={13}/>{t("适合推车午睡")}</span>}{item.freePlay&&<span>{t("自由玩耍")}</span>}{item.indoor&&<span><Umbrella size={13}/>{t("室内备用")}</span>}{display(item,'bathrooms')&&<span className="bathroom">{t("洗手间：")}{display(item,'bathrooms')}</span>}</div>;}

function Home() {
 const {t,language,display}=useLocale();
 const {state,update,ready,saveError,offlineReady,online}=useTrip();
 const [tab,setTab]=useState<Tab>('itinerary'),[selectedDate,setSelectedDate]=useState('2026-10-23');
 const [now,setNow]=useState<Date|null>(null),[editMode,setEditMode]=useState(false),[tired,setTired]=useState(false);
 const [planReason,setPlanReason]=useState<PlanReason|null>(null),[nextOpen,setNextOpen]=useState(false),[overview,setOverview]=useState(false);
 const [editingItem,setEditingItem]=useState<ItineraryItem|null>(null),[editingBooking,setEditingBooking]=useState<Booking|null>(null),[addingPlace,setAddingPlace]=useState(false);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState<Category|'all'|'remi'>('all'),[onlyFavorites,setOnlyFavorites]=useState(false);
 const [toast,setToast]=useState('');
 const nextRef=useRef<HTMLDivElement>(null);
 const [focusedItem,setFocusedItem]=useState<string|null>(null);
 useEffect(()=>{
  if(tab!=='itinerary'||!focusedItem)return;
  const frame=requestAnimationFrame(()=>{const card=document.getElementById(`itinerary-${focusedItem}`);card?.querySelector('details')?.setAttribute('open','');card?.scrollIntoView({behavior:'smooth',block:'start'});card?.focus({preventScroll:true});});
  return()=>cancelAnimationFrame(frame);
 },[tab,focusedItem]);
 useEffect(()=>{
  const date=new Date();setNow(date);
  const current=days.find(d=>localClock(date,d.timeZone).date===d.date);if(current)setSelectedDate(current.date);
  const fromHash=window.location.hash.slice(1);if(tabs.some(t=>t.id===fromHash))setTab(fromHash as Tab);
  const hash=()=>{const value=window.location.hash.slice(1);if(tabs.some(t=>t.id===value))setTab(value as Tab);};window.addEventListener('hashchange',hash);
  const timer=window.setInterval(()=>setNow(new Date()),30000);
  return ()=>{clearInterval(timer);window.removeEventListener('hashchange',hash);};
 },[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{document.querySelector('.date.active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});},[selectedDate]);
 const places=mergePlaces(basePlaces,state,baseBookings);
 const bookings=baseBookings.map(b=>({...b,...state.bookingEdits[b.id]}));
 const items=mergeItems(itinerary,places,bookings,state);
 const day=days.find(d=>d.date===selectedDate)!;
 const selectedItems=dayItems(items,selectedDate,state);
 const next=now?nextActivity(selectedItems,day,state,now):{item:selectedItems[0],mode:'preview'};
 const visibleItems=tired&&now?simpleDay(selectedItems,day,state,now):selectedItems;
 const hotel=places.find(p=>p.id===day.hotelId);
 const hotelBooking=bookings.find(b=>b.type==='hotels'&&b.placeId===day.hotelId);
 const today=now?localClock(now,day.timeZone).date===selectedDate:false;
 const count=now?countdown(now,trip.startDate):null;
 const nav=(value:Tab)=>{setTab(value);window.location.hash=value;setSearch('');setFilter('all');};
 const selectDate=(date:string)=>{setSelectedDate(date);setTired(false);setFocusedItem(null);};
 const mutate=(apply:(s:LocalState)=>LocalState,message?:string)=>{update(apply);if(message)setToast(message);};
 const progress=(item:ItineraryItem,value:'completed'|'skipped')=>mutate(s=>{const p={...s.progress};if(p[item.id]===value)delete p[item.id];else p[item.id]=value;return {...s,progress:p};});
 const addActivity=(place?:Place)=>setEditingItem({id:'new',date:selectedDate,title:place?.name||'',titleZh:place?.nameZh,placeId:place?.id,category:place?.category||'attractions',priority:place?.priority||'optional',bookingStatus:place?.availability==='sold-out'?'sold-out':'tbd',childFriendly:place?.childFriendly,strollerFriendly:place?.strollerFriendly,napFriendly:place?.napFriendly,indoor:place?.indoor});
 useWebMCP({state,items,days,selectedDate,selectDate,update,ready});
 const filtered=places.filter(p=>(filter==='all'||filter==='remi'?(filter!=='remi'||p.tags?.includes('REMI')):p.category===filter)&&(!onlyFavorites||state.favorite[p.id])&&(!search||[p.name,p.nameZh,p.neighborhood,p.address,p.notes,display(p,'neighborhood'),display(p,'notes'),state.placeNotes[p.id]].join(' ').toLowerCase().includes(search.toLowerCase())));
 const saveItem=(patch:Partial<ItineraryItem>)=>{
  if(!editingItem)return;
  if(editingItem.id==='new')mutate(s=>({...s,addedItems:[...s.addedItems,{...editingItem,...patch,id:`activity-${crypto.randomUUID()}`}]}),'已添加到行程');
  else mutate(s=>changeItem(s,editingItem,patch),'活动已保存');
  if(patch.date)setSelectedDate(patch.date);setEditingItem(null);
 };
 function exportBackup(){let raw=JSON.stringify(state,null,2);if(saveError.includes('原数据')){try{raw=localStorage.getItem(STORAGE_KEY)||raw;}catch{/* Use the current in-memory state when storage is unavailable. */}}const blob=new Blob([raw],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='spain-journal-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const nextPanel=next.item?<><span className="eyebrow">{next.mode==='overdue'?t('时间已过 · 请确认是否继续'):next.mode==='today'?t('下一站 · NEXT STOP'):next.mode==='past'?t('这一天 · 尚未完成'):t('这一天的下一站')}</span><h3>{next.item.startTime&&<span className="next-time">{next.item.startTime} · </span>}{(language==='en'?next.item.title:(next.item.titleZh||next.item.title))}</h3><p>{display(next.item,'duration')||display(next.item,'timeNote')||t('时间灵活')}{display(next.item,'duration')&&display(next.item,'timeNote')?' · '+display(next.item,'timeNote'):''}</p><div className="next-status"><Status status={next.item.bookingStatus}/></div></>:<><span className="eyebrow">{t("今日留白")}</span><h3>{t("接下来，好好休息。")}</h3><p>{t("没有待开始的活动了。随时查看清单或回住处。")}</p></>;
 return <div className={'app-shell '+(tab==='map'?'map-mode':'')}>
  <header className="masthead"><button className="wordmark" onClick={()=>setOverview(true)}>{t("西班牙慢游")}<span>OUR FAMILY JOURNAL</span></button><div className="header-controls"><LanguageSwitch/><button className="trip-year" onClick={()=>setOverview(true)} aria-label={t("旅行概览与离线状态")}>{!online?<><WifiOff size={14}/> {t(" 离线")}</>:offlineReady?t('已可离线使用'):'EST. 2026'}</button></div></header>
  {tab!=='map'&&<section className="trip-cover"><div className="cover-text"><span className="eyebrow">A LITTLE ADVENTURE, TOGETHER</span><h1>SPAIN<span>{t("西班牙，一起慢慢走。")}</span></h1><p>22–29 OCTOBER 2026</p><div className="cover-meta">Barcelona · Madrid <span>{t("2 位大人 + 小小 Remi")}</span></div></div><div className="cover-photo" role="img" aria-label={t("桂尔公园的彩色马赛克建筑与巴塞罗那全景")}/></section>}
  <main>
  {saveError&&<div className="save-error" role="alert">{t(saveError)}<button onClick={exportBackup}>{t("导出本机备份")}</button></div>}
  {tab!=='map'&&count!==null&&count>0&&<div className="countdown"><span className="tiny-sun">✳</span> {t(" 距离西班牙旅行还有 ")}<strong>{count}</strong> {t(" 天 ")}<span className="countdown-end">{t("慢慢期待，好好出发。")}</span></div>}
  {(tab==='itinerary'||tab==='map')&&<div className="date-strip" aria-label={t("选择行程日期")}>{days.map(d=><button key={d.date} className={selectedDate===d.date?'date active':'date'} aria-pressed={selectedDate===d.date} aria-label={language==='en'?`October ${d.date.slice(-2)}, ${t(d.weekdayZh)}`:`10月${d.date.slice(-2)}日 ${d.weekdayZh}`} onClick={()=>selectDate(d.date)}><small>{d.weekday}</small><strong>{d.date.slice(-2)}</strong><span>{t("10 月")}</span>{now&&localClock(now,d.timeZone).date===d.date&&<i/>}</button>)}</div>}
  {!ready?<p className="loading" role="status">{t("正在打开你的旅行手帐…")}</p>:tab==='itinerary'?<div className="content-grid"><section aria-label={t("每日行程")}>
   <div className="day-heading"><div><div className="eyebrow">{today?'TODAY · ':`DAY ${String(days.indexOf(day)+1).padStart(2,'0')} · `}{language==='en'?t(day.weekdayZh):`${day.weekday} / ${day.weekdayZh}`}</div><h2 className={day.city.length>12?'long-city':''}>{day.city}{language==='zh'&&<span>{day.cityZh}</span>}</h2><p>{t(day.theme)}</p></div><button className={'icon-button '+(editMode?'enabled':'')} onClick={()=>setEditMode(!editMode)} aria-label={editMode?t('结束编辑'):t('编辑行程')} aria-pressed={editMode}><Pencil size={18}/></button></div>
   <div className="remi-controls"><button className="remi-toggle" role="switch" aria-checked={state.remiMode} onClick={()=>mutate(s=>({...s,remiMode:!s.remiMode}))}><Baby size={21}/> Remi Mode <span className={'switch '+(state.remiMode?'on':'')}/></button><button className={'text-button '+(tired?'active':'')} aria-pressed={tired} onClick={()=>setTired(!tired)}>{tired?t('查看完整一天'):t('Remi 累了')}</button><button className="text-button" onClick={()=>setPlanReason('rain')}><CloudRain size={16}/> Plan B</button></div>
   {tired&&<div className="gentle-note"><Moon size={18}/><span>{t("轻松一点：保留必做、吃饭和省力的停留。已完成和跳过的活动已收起。")}</span></div>}
   <div className="next-card" ref={nextRef}><div>{nextPanel}</div>{next.item?.googleMapsQuery&&<MapLink query={next.item.googleMapsQuery} className="nav-button"/>}</div>
   <button className="whats-next" onClick={()=>{setNow(new Date());setNextOpen(true);}}><Route size={17}/>{t("接下来做什么？")}<span>{today?t('按当地时间'):t('预览所选日期')}</span></button>
   {day.checklist&&<section className="checklist"><h3>{selectedDate==='2026-10-29'?t('出发前，一步一步来'):t('出发准备清单')}</h3>{day.checklist.map(check=><label key={check.id}><input type="checkbox" checked={!!state.checks[`${day.date}-${check.id}`]} onChange={()=>mutate(s=>({...s,checks:{...s.checks,[`${day.date}-${check.id}`]:!s.checks[`${day.date}-${check.id}`]}}))}/><span>{t(check.label)}</span></label>)}{selectedDate==='2026-10-29'&&<a className="source-link" href={sourceNotes.taxRefund} target="_blank" rel="noreferrer">{t("查看 Aena 官方退税流程")}</a>}</section>}
   <div className="section-caption"><span>{tired?t('剩下的轻松行程'):t('今天的节奏')}</span><small>{selectedItems.filter(i=>state.progress[i.id]==='completed').length} / {selectedItems.length} {t(" 已完成")}</small></div>
   {editMode&&<div className="edit-banner"><p>{t("用上下按钮调整路线；编辑卡片可改时间、移到另一天。")}</p><button onClick={()=>addActivity()}><Plus size={17}/>{t("添加活动")}</button></div>}
   <div className="timeline">{visibleItems.map((item,index)=>{
    const completed=state.progress[item.id]==='completed',skipped=state.progress[item.id]==='skipped';
    return <article tabIndex={-1} id={`itinerary-${item.id}`} className={'timeline-row '+(focusedItem===item.id?'map-focused ':'')+(completed||skipped?'is-done ':'')+(state.remiMode&&item.demanding&&item.priority==='optional'?'demanding ':'')} key={item.id} data-testid={`activity-${item.id}`}>
    <div className="time"><strong>{item.startTime||t('待定')}</strong><span>{item.endTime||(!item.startTime?t('灵活安排'):item.bookingStatus==='booked'?t('已安排'):t('计划时间'))}</span></div>
    <div className={'activity-card '+(state.remiMode&&item.childFriendly?'child-highlight':'')}><div className="activity-top"><div className="card-badges"><span className={'badge '+(item.priority==='must'?'must':'')}>{t(priorityLabels[item.priority])}</span>{item.bookingStatus!=='no-reservation'&&<Status status={item.bookingStatus}/>}</div><button className={'complete '+(completed?'checked':'')} aria-label={`${completed?t('取消完成'):t('完成')} ${(language==='en'?item.title:(item.titleZh||item.title))}`} aria-pressed={completed} onClick={()=>progress(item,'completed')}>{completed?<Check size={21}/>:skipped?<SkipForward size={19}/>:<Circle size={21}/>}</button></div>
    <h3>{(language==='en'?item.title:(item.titleZh||item.title))}</h3>{language==='zh'&&item.titleZh&&<p className="original-title">{item.title}</p>}{skipped&&<span className="badge skipped">{t("已跳过 · 可恢复")}</span>}
    <p className="description">{display(item,'description')}</p>{display(item,'timeNote')&&<p className="time-note">{display(item,'timeNote')}</p>}
    {(state.remiMode||item.napFriendly)&&<FamilyTags item={state.remiMode?item:{napFriendly:item.napFriendly}}/>}
    {display(item,'notes')&&<p className="personal-note">{display(item,'notes')}</p>}
    <div className="card-footer"><span>{display(item,'duration')||display(item,'neighborhood')||t(categoryLabels[item.category])}</span><MapLink query={item.googleMapsQuery}/></div>
    <details className="activity-details"><summary>{t("更多信息与备注")}<ChevronDown size={14}/></summary><div className="details-body">{item.address&&<p><MapPin size={15}/>{item.address}</p>}{display(item,'walkingContext')&&<p>{display(item,'walkingContext')}</p>}<p>{t("预订：")}{t(bookingLabels[item.bookingStatus])}{item.confirmationNumber?t(' · 确认号 ')+item.confirmationNumber:''}</p>{item.indoor!==undefined&&<p>{item.indoor?t('室内活动'):t('户外活动')}</p>}{display(item,'bathrooms')&&<p>{t("洗手间：")}{display(item,'bathrooms')}</p>}{safeUrl(item.ticketUrl)&&<a className="outline-button" href={safeUrl(item.ticketUrl)} target="_blank" rel="noreferrer"><Ticket size={16}/>{t("打开票券")}</a>}{safeUrl(item.bookingUrl)&&<a className="source-link" href={safeUrl(item.bookingUrl)} target="_blank" rel="noreferrer">{t("官方 / 预订信息")}</a>}<div className="detail-actions"><button onClick={()=>setEditingItem(item)}><Pencil size={15}/>{t("编辑 / 加笔记")}</button><button onClick={()=>progress(item,'skipped')}><SkipForward size={15}/>{skipped?t('恢复活动'):t('跳过')}</button>{item.bookingStatus==='need-to-book'&&<button onClick={()=>mutate(s=>changeItem(s,item,{bookingStatus:'booked'}),'已标为预订')}><Check size={15}/>{t("标为已预订")}</button>}</div></div></details>
    {editMode&&<div className="reorder"><button aria-label={`${t('上移')} ${(language==='en'?item.title:(item.titleZh||item.title))}`} disabled={index===0} onClick={()=>mutate(s=>reorder(s,selectedItems,item.id,-1))}><ChevronUp size={19}/></button><button aria-label={`${t('下移')} ${(language==='en'?item.title:(item.titleZh||item.title))}`} disabled={index===visibleItems.length-1} onClick={()=>mutate(s=>reorder(s,selectedItems,item.id,1))}><ChevronDown size={19}/></button><button onClick={()=>setEditingItem(item)}>{t("编辑活动")}</button><button onClick={()=>progress(item,'skipped')}>{skipped?t('恢复'):t('跳过')}</button></div>}
    </div></article>;
   })}</div>
   {visibleItems.length===0&&<div className="empty"><Coffee size={28}/><h3>{t("余下时间，留给休息。")}</h3><p>{t("可以回住处，或从收藏里选一个轻松的地点。")}</p></div>}
   {tired&&hotel&&<div className="return-card"><BedDouble size={22}/><div><span>{t("随时回去休息")}</span><h3>{hotel.name}</h3>{hotel.needsVerification&&<small>{t("准确地址待补充，请先核对订单")}</small>}</div><MapLink query={placeQuery(hotel)}/></div>}
   <button className="add-activity" onClick={()=>addActivity()}><Plus size={18}/>{t("为这一天添加活动")}</button>
   <details className="mobile-day-note"><summary>{t("今日提醒与住宿")}</summary><p>{t(day.note)}</p>{hotel&&<><h4>{hotel.name}</h4><MapLink query={hotelBooking?.address||placeQuery(hotel)}/></>}</details>
  </section><aside><div className="aside-card"><span className="eyebrow">OUR TRIP, AT A GLANCE</span><h3>{t("八天，三个人。")}</h3><p>{t("2 位大人 · Remi，3 岁")}</p><p>{t("3 件大行李箱 · 1 辆推车")}</p>{hotel&&<><hr/><MapPin size={20}/><h4>{t("今晚住这里")}</h4><p>{hotel.name}</p><Status status={hotelBooking?.status||'tbd'}/><MapLink query={hotelBooking?.address||placeQuery(hotel)}/></>}<button className="aside-overview" onClick={()=>setOverview(true)}>{t("旅行概览与离线使用")}</button></div><div className="aside-note"><span>{t("一点小提醒")}</span><p>{t(day.note)}</p></div><div className="route-note"><span className="eyebrow">LOCAL TIME</span><p>{now?localClock(now,day.timeZone).time:'—'} <small>{day.timeZone==='Europe/Madrid'?t('西班牙时间'):t('纽约时间')}</small></p></div></aside></div>
  :tab==='bookings'?<section className="bookings-view"><div className="page-heading"><span className="eyebrow">EVERYTHING IN ONE PLACE</span><h2>{t("旅途里的，每一张票。")}</h2><p>{t("订好了的安心收着，待确认的慢慢补齐。")}</p></div><div className="booking-summary"><span><strong>{bookings.filter(b=>b.status==='booked').length}</strong> {t(" 已预订")}</span><span><strong>{bookings.filter(b=>b.status==='need-to-book').length}</strong> {t(" 待预订")}</span><span><strong>{bookings.filter(b=>b.status==='sold-out').length}</strong> {t(" 留意退票")}</span></div><div className="booking-groups">{bookingGroups.map(group=><section key={group.id} className="booking-group"><h3><group.Icon size={20}/>{t(group.label)}<span>{language==='zh'?group.en:''}</span></h3>{bookings.filter(b=>b.type===group.id).map(booking=>{
    const place=places.find(p=>p.id===booking.placeId);
    return <article className="booking-card" key={booking.id}><div className="booking-card-top"><span className="booking-date">{booking.date.slice(5).replace('-',' / ')}{booking.endDate?' – '+booking.endDate.slice(5).replace('-',' / '):''}</span><Status status={booking.status}/></div><h4>{display(booking,'title')}</h4><p className="booking-time">{booking.time||t('时间待定')}{display(booking,'timeNote')?' · '+display(booking,'timeNote'):''}</p>{booking.confirmationNumber&&<p className="confirmation">{t("确认号 ")}<strong>{booking.confirmationNumber}</strong></p>}<p className="description">{display(booking,'notes')}</p><div className="booking-actions">{safeUrl(booking.ticketUrl)?<a className="outline-button" href={safeUrl(booking.ticketUrl)} target="_blank" rel="noreferrer"><Ticket size={15}/>{t("打开票券")}</a>:<span className="ticket-missing">{t("票券尚未添加")}</span>}{safeUrl(booking.reservationUrl)&&<a className="source-link" href={safeUrl(booking.reservationUrl)} target="_blank" rel="noreferrer">{t("官网 / 预订")}</a>}<button className="icon-button" aria-label={`${t('编辑预订')} ${display(booking,'title')}`} onClick={()=>setEditingBooking(booking)}><Pencil size={16}/></button></div><details className="activity-details"><summary>{t("地址、取消政策与票券")}<ChevronDown size={14}/></summary><div className="details-body"><p>{booking.address||place?.address||t('准确地址以订单为准')}</p>{place&&<MapLink query={booking.address||placeQuery(place)}/>}<p>{display(booking,'cancellationNotes')||t('退改政策待从订单补充。')}</p>{booking.ticketImage?<img className="ticket-image" src={booking.ticketImage} alt={`${display(booking,'title')} ${t('票券二维码')}`}/>:<p>{t("尚无本地票券图片，可先在编辑中填写票券链接。")}</p>}</div></details></article>;
   })}</section>)}</div></section>
  :tab==='map'?<DailyRouteMap day={day} items={selectedItems} places={places} state={state} nextId={next.item?.id} onViewItem={id=>{setTired(false);setFocusedItem(id);nav('itinerary');}}/>
  :<section className="places-view"><div className="page-heading"><span className="eyebrow">LITTLE PLACES, LOVELY MEMORIES</span><div className="heading-row"><h2>{t('想去的地方。')}</h2>{tab==='places'&&<button className="icon-button" aria-label={t("添加新地点")} onClick={()=>setAddingPlace(true)}><Plus size={20}/></button>}</div><p>{t('小店、好吃的，还有 Remi 的快乐。')}</p></div>
    <label className="search-box"><Search size={19}/><input aria-label={t("搜索地点")} placeholder={t("搜索名字、街区，或你的笔记")} value={search} onChange={e=>setSearch(e.target.value)}/></label>
    <div className="filter-strip" aria-label={t("地点类别筛选")}><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>{t("全部")}</button>{(Object.entries(categoryLabels) as [Category,string][]).map(([id,label])=><button className={filter===id?'active':''} key={id} onClick={()=>setFilter(id)}>{t(label)}</button>)}<button className={filter==='remi'?'active':''} onClick={()=>setFilter('remi')}><Baby size={15}/>REMI</button></div>
    <div className="places-toolbar"><span>{filtered.length} {t(" 个地点")}</span>{tab==='places'&&<button aria-pressed={onlyFavorites} className={onlyFavorites?'active':''} onClick={()=>setOnlyFavorites(!onlyFavorites)}><Heart size={16} fill={onlyFavorites?'currentColor':'none'}/>{t("只看心选")}</button>}</div>
    {filtered.length===0&&<div className="empty"><Search size={26}/><h3>{t("还没有符合条件的地点")}</h3><p>{t("换个关键词或筛选，或添加你发现的新地方。")}</p></div>}
    <div className="place-grid">{filtered.map(place=><article className={'place-card '+(state.visited[place.id]?'visited':'')} key={place.id}><div className="place-card-top"><span className="eyebrow">{t(categoryLabels[place.category])} · {display(place,'neighborhood')}</span><button className="favorite-button" aria-label={`${state.favorite[place.id]?t('取消收藏'):t('收藏地点')} ${place.name}`} aria-pressed={!!state.favorite[place.id]} onClick={()=>mutate(s=>({...s,favorite:{...s.favorite,[place.id]:!s.favorite[place.id]}}))}><Heart size={20} fill={state.favorite[place.id]?'currentColor':'none'}/></button></div><h3>{(language==='en'?place.name:(place.nameZh||place.name))}</h3>{language==='zh'&&place.nameZh&&<p className="original-title">{place.name}</p>}<div className="place-badges"><span className={'badge '+(place.priority==='must'?'must':'')}>{place.priority==='must'?t('Must · 必去'):place.priority==='recommended'?t('Want to visit · 想去'):t('If nearby · 顺路再去')}</span>{place.availability&&<span className="badge status-sold-out">{place.availability==='unavailable'?t('旅行期间不可用'):t('线上售罄')}</span>}{place.tags?.includes('REMI')&&<span className="badge remi">REMI</span>}</div>{place.address&&<p className="place-address">{place.address}</p>}{display(place,'walkingContext')&&<p className="description">{display(place,'walkingContext')}</p>}{place.needsVerification&&<p className="verification-note">{t("具体地址 / 营业待确认")}</p>}{display(place,'notes')&&<p className="description">{display(place,'notes')}</p>}<div className="place-actions"><button className={state.visited[place.id]?'visited-control selected':'visited-control'} onClick={()=>mutate(s=>({...s,visited:{...s.visited,[place.id]:!s.visited[place.id]}}))} aria-pressed={!!state.visited[place.id]}>{state.visited[place.id]?<Check size={16}/>:<Circle size={16}/>}{t("去过了")}</button><MapLink query={placeQuery(place)}/></div><details className="activity-details"><summary>{t("笔记与行程安排")}<ChevronDown size={14}/></summary><div className="details-body"><label className="place-note-label">{t("我的笔记")}<textarea aria-label={`${place.name} ${t('的笔记')}`} value={state.placeNotes[place.id]||''} onChange={e=>mutate(s=>({...s,placeNotes:{...s.placeNotes,[place.id]:e.target.value}}))} rows={2} maxLength={6000} placeholder={t("记下喜欢的款式、想吃的菜…")}/></label><FamilyTags item={place}/><button className="outline-button" disabled={place.availability==='unavailable'} onClick={()=>addActivity(place)}><Plus size={16}/>{t("安排到某一天")}</button></div></details></article>)}</div>
    {tab==='places'&&<><div className="food-preference"><Coffee size={20}/><p>{t(foodPreference)}</p></div><div className="collections">{collections.map(collection=><div key={t(collection.title)}><h3>{t(collection.title)}</h3><p className="field-help">{t("还没选具体店，留待发现。")}</p><div>{collection.categories.map(label=><span key={t(label)}>{t(label)}</span>)}</div></div>)}</div></>}
  </section>}
  {tab!=='map'&&<footer className="journal-footer"><span>{t("一点计划，多一点随心。")}</span><button onClick={()=>setOverview(true)}>{t("旅行概览 · 离线使用 · 图片来源")}</button></footer>}
  </main>
  <nav className="bottom-nav" aria-label={t("主导航")}>{tabs.map(({id,zh,en,Icon})=><button key={id} className={tab===id?'selected':''} aria-current={tab===id?'page':undefined} onClick={()=>nav(id)}><Icon size={21}/><span>{language==='en'?en:zh}{language==='zh'&&<small>{en}</small>}</span></button>)}</nav>
  {toast&&<div className="toast" role="status"><Check size={16}/>{t(toast)}</div>}
  {editingItem&&<ItemEditor item={editingItem} days={days} places={places} onSave={saveItem} onClose={()=>setEditingItem(null)}/>}
  {editingBooking&&<BookingEditor booking={editingBooking} days={days} onSave={patch=>{mutate(s=>changeBooking(s,editingBooking,patch,items),'预订已保存');setEditingBooking(null);}} onClose={()=>setEditingBooking(null)}/>}
  {addingPlace&&<PlaceEditor onClose={()=>setAddingPlace(false)} onSave={place=>{mutate(s=>({...s,addedPlaces:[...s.addedPlaces,place]}),'地点已保存');setAddingPlace(false);setFilter('all');setSearch('');setOnlyFavorites(false);}}/>}
  {nextOpen&&<Sheet title={t("接下来做什么？")} description={`${day.date.slice(5).replace('-','/')} · ${t(day.cityZh)} · ${today?t('按当地时间计算'):t('预览所选日期，不代表今天')}`} onClose={()=>setNextOpen(false)}><div className="next-detail">{nextPanel}{next.item&&<><p className="description">{display(next.item,'description')}</p>{display(next.item,'walkingContext')&&<p className="walking-context">{display(next.item,'walkingContext')}</p>}<FamilyTags item={next.item}/><MapLink query={next.item.googleMapsQuery} className="primary-button" label={t("Google Maps 导航")}/><div className="detail-actions"><button onClick={()=>{progress(next.item!,'completed');}}>{t("已完成，看看下一站")}</button><button onClick={()=>progress(next.item!,'skipped')}>{t("跳过这一站")}</button></div></>}{!next.item&&hotel&&<MapLink query={placeQuery(hotel)} label={t("回住处")}/>}</div></Sheet>}
  {planReason&&<Sheet title={t("计划有变，也没关系。")} description={`${day.date.slice(5).replace('-','/')} · Plan B · ${t('只显示这一天的备选')}`} onClose={()=>setPlanReason(null)}><div className="plan-reasons">{reasons.map(({id,label,Icon})=><button key={id} className={planReason===id?'active':''} onClick={()=>setPlanReason(id)}><Icon size={19}/>{t(label)}</button>)}</div><div className="plan-options">{day.planB.filter(p=>p.reasons.includes(planReason)).map(plan=>{const place=places.find(p=>p.id===plan.placeId);return <article key={plan.id}><span className="eyebrow">{place?display(place,'neighborhood'):t('轻松一点')}</span><h3>{t(plan.title)}</h3><p>{t(plan.description)}</p>{place&&<MapLink query={placeQuery(place)}/>}</article>;})}</div>{planReason==='tired'&&<button className="primary-button" onClick={()=>{setTired(true);setPlanReason(null);}}>{t("切换到轻松行程")}</button>}</Sheet>}
  {overview&&<Sheet title={t("我们的西班牙旅行")} description="22–29 OCTOBER 2026 · Barcelona & Madrid" onClose={()=>setOverview(false)}><div className="overview"><h3>{t("2 位大人 + Remi（3 岁）")}</h3><p>{t("3 件大行李箱 · 1 辆推车")}</p><div className="overview-route"><span>{t("10/22 · Newark 出发")}</span><span>10/23–28 · Barcelona</span><span>10/28–29 · Madrid</span><span>{t("10/29 · 飞往 Chongqing")}</span></div><h3>{t("随身使用")}</h3><p>{offlineReady?t('此设备已缓存应用和行程，可离线查看。'):t('离线缓存尚未就绪。正式版本首次联网打开后会缓存行程。')}</p><p>{t("在 iPhone Safari 打开正式 HTTPS 网址，点「分享」→「添加到主屏幕」。首次保持联网，等顶部显示「已可离线使用」。")}</p><p>{t("导航与外部购票仍需要网络。修改只存在这台设备的这个浏览器，清除网站数据会删除修改；家人之间不会自动同步。")}</p><button className="outline-button" onClick={exportBackup}><Download size={17}/>{t("导出本机备份")}</button><h3>{t("尚需你补齐")}</h3><p>{t("两段航班准确时间、公寓地址与门禁、确认号及票券。候选活动的场次、余票与店铺营业需确认；已预订状态按你提供的信息记录。")}</p><h3>{t("图片与资料")}</h3><p className="photo-credit">{t("首页采用你提供的桂尔公园图片。")}</p><a className="source-link" href={sourceNotes.taxRefund} target="_blank" rel="noreferrer">{t("Aena 官方退税流程")}</a></div></Sheet>}
 </div>;
}

export default function Page(){return <LanguageProvider><Home/></LanguageProvider>;}
